voting-app:
  build: ./voting-app/.
  volumes:
    - ./voting-app:/app
  ports:
    - "5000:80"

redis:
  #image: redis
  image: hypriot/rpi-redis:latest
  ports: ["6379"]

worker:
  build: ./worker

db:
  #image: postgres:9.4
  image: ldouchy/rpi-postgres:latest
  volumes:
    - "myvolume:/var/lib/postgresql/data"

result-app:
  build: ./result-app/.
  volumes:
    - ./result-app:/app
  ports:
    - "5001:80"
