voting-app:
  build: ./voting-app/.
  ports:
    - "5000:80"

redis:
  image: hypriot/rpi-redis:latest
  ports: ["6379"]

worker:
  build: ./worker

db:
  build: ./postgres-arm/
  volumes:
    - "myvolume:/var/lib/postgresql/data"

result-app:
  build: ./result-app/.
  ports:
    - "5001:80"
