version: '2'

services:
  voting-app:
    image: docker pull thecaptainsshack/rpi-voting-app
    ports:
      - "5000:80"

  redis:
    image: hypriot/rpi-redis:latest
    expose: ["6379"]

  worker:
    image: thecaptainsshack/rpi-worker

  db:
    image: thecaptainsshack/postgres-arm
    volumes:
      - pg-volume:/var/lib/postgresql/data

  result-app:
    image: thecaptainsshack/rpi-result-app
    ports:
      - "5001:80"

volumes:
  pg-volume: {}

networks:
  default:
    driver: overlay
